<a href="https://colab.research.google.com/github/alarconcita/InTechMom/blob/main/Asignaci%C3%B3n_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas mysql-connector-python

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (8.3.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd
import mysql.connector
from mysql.connector import Error

In [3]:
df = pd.read_csv('/content/drive/MyDrive/michelin_my_maps.csv')

In [4]:
print(df.head())

             Name                                            Address  \
0         L'OSIER       7-5-5 Ginza, Chuo-ku, Tokyo, 104-0061, Japan
1  Azabu Kadowaki  2-7-2 Azabujuban, Minato-ku, Tokyo, 106-0045, ...
2          Kohaku  3-4 Kagurazaka, Shinjuku-ku, Tokyo, 162-0825, ...
3        Harutaka   6F, 8-3-1 Ginza, Chuo-ku, Tokyo, 104-0061, Japan
4           Kanda  1F, Toranomon Hills Residential Tower, 1-1-1 A...

       Location Price               Cuisine   Longitude   Latitude  \
0  Tokyo, Japan  ¥¥¥¥  French, Contemporary  139.761203  35.669667
1  Tokyo, Japan  ¥¥¥¥              Japanese  139.733551  35.655993
2  Tokyo, Japan  ¥¥¥¥              Japanese  139.741008  35.700701
3  Tokyo, Japan  ¥¥¥¥                 Sushi  139.759203  35.669269
4  Tokyo, Japan  ¥¥¥¥              Japanese  139.748000  35.665800

    PhoneNumber                                                Url  \
0  8.133572e+10  https://guide.michelin.com/en/tokyo-region/tok...
1  8.135772e+10  https://guide.michelin.com/en/tokyo-region/tok...
2  8.150314e+11  https://guide.michelin.com/en/tokyo-region/tok...
3  8.133573e+10  https://guide.michelin.com/en/tokyo-region/tok...
4  8.136459e+10  https://guide.michelin.com/en/tokyo-region/tok...

                         WebsiteUrl    Award  \
0    https://losier.shiseido.co.jp/  3 Stars
1                               NaN  3 Stars
2      http://kagurazaka-kohaku.jp/  3 Stars
3                               NaN  3 Stars
4  http://www.nihonryori-kanda.com/  3 Stars

                               FacilitiesAndServices  \
0    Air conditioning,Car park,Interesting wine list
1                    Air conditioning,Counter dining
2  Air conditioning,Counter dining,Interesting wi...
3                    Air conditioning,Counter dining
4  Air conditioning,Counter dining,Interesting wi...

                                         Description
0  In 2023 L’OSIER celebrated the 50th anniversar...
1  Toshiya Kadowaki’s aim is to serve up “unforge...
2  Koji Koizumi creates a cuisine all his own as ...
3  Sometimes our connections intervene to change ...
4  Hiroyuki Kanda understands the essence of Japa...

In [5]:
print(df.columns)

Index(['Name', 'Address', 'Location', 'Price', 'Cuisine', 'Longitude',
       'Latitude', 'PhoneNumber', 'Url', 'WebsiteUrl', 'Award',
       'FacilitiesAndServices', 'Description'],
      dtype='object')

In [7]:
# Agregar columnas 'Country' y 'Locality' dividiendo la columna 'Location'
df[['Locality', 'Country']] = df['Location'].str.rsplit(', ', n=1, expand=True)
print(df.columns)
df.head()

Index(['Name', 'Address', 'Location', 'Price', 'Cuisine', 'Longitude',
       'Latitude', 'PhoneNumber', 'Url', 'WebsiteUrl', 'Award',
       'FacilitiesAndServices', 'Description', 'Locality', 'Country'],
      dtype='object')

,Name,Address,Location,Price,Cuisine,Longitude,Latitude,PhoneNumber,Url,WebsiteUrl,Award,FacilitiesAndServices,Description,Locality,Country
0,L'OSIER,"7-5-5 Ginza, Chuo-ku, Tokyo, 104-0061, Japan","Tokyo, Japan",¥¥¥¥,"French, Contemporary",139.761203,35.669667,8.133572e+10,https://guide.michelin.com/en/tokyo-region/tok...,https://losier.shiseido.co.jp/,3 Stars,"Air conditioning,Car park,Interesting wine list",In 2023 L’OSIER celebrated the 50th anniversar...,Tokyo,Japan
1,Azabu Kadowaki,"2-7-2 Azabujuban, Minato-ku, Tokyo, 106-0045, ...","Tokyo, Japan",¥¥¥¥,Japanese,139.733551,35.655993,8.135772e+10,https://guide.michelin.com/en/tokyo-region/tok...,NaN,3 Stars,"Air conditioning,Counter dining",Toshiya Kadowaki’s aim is to serve up “unforge...,Tokyo,Japan
2,Kohaku,"3-4 Kagurazaka, Shinjuku-ku, Tokyo, 162-0825, ...","Tokyo, Japan",¥¥¥¥,Japanese,139.741008,35.700701,8.150314e+11,https://guide.michelin.com/en/tokyo-region/tok...,http://kagurazaka-kohaku.jp/,3 Stars,"Air conditioning,Counter dining,Interesting wi...",Koji Koizumi creates a cuisine all his own as ...,Tokyo,Japan
3,Harutaka,"6F, 8-3-1 Ginza, Chuo-ku, Tokyo, 104-0061, Japan","Tokyo, Japan",¥¥¥¥,Sushi,139.759203,35.669269,8.133573e+10,https://guide.michelin.com/en/tokyo-region/tok...,NaN,3 Stars,"Air conditioning,Counter dining",Sometimes our connections intervene to change ...,Tokyo,Japan
4,Kanda,"1F, Toranomon Hills Residential Tower, 1-1-1 A...","Tokyo, Japan",¥¥¥¥,Japanese,139.748000,35.665800,8.136459e+10,https://guide.michelin.com/en/tokyo-region/tok...,http://www.nihonryori-kanda.com/,3 Stars,"Air conditioning,Counter dining,Interesting wi...",Hiroyuki Kanda understands the essence of Japa...,Tokyo,Japan

In [10]:
df.Price.unique()

array(['Muy costoso'], dtype=object)

In [11]:
# Columna 'Price'
currency_symbols = ['¥', '£', '€', '$', '₩', '₺', '฿', '₫']
df['Price'] = df['Price'].replace({symbol: '' for symbol in currency_symbols})

df['Price'] = df['Price'].apply(lambda x: 'Muy Barato' if pd.isna(x) or len(str(x)) == 0
                                  else 'Accesible' if len(str(x)) == 1
                                  else 'Normal' if len(str(x)) == 2
                                  else 'Costoso' if len(str(x)) == 3
                                  else 'Muy costoso' if len(str(x)) >= 4
                                  else x)

print(df[['Name', 'Price']].head())

             Name        Price
0         L'OSIER  Muy costoso
1  Azabu Kadowaki  Muy costoso
2          Kohaku  Muy costoso
3        Harutaka  Muy costoso
4           Kanda  Muy costoso

In [13]:
# Dividir 'Cuisine'
max_cuisine_labels = df['Cuisine'].str.count(',').max() + 1 if not pd.isna(df['Cuisine']).all() else 1
cuisine_columns = [f'Cuisine {i}' for i in range(1, max_cuisine_labels + 1)]
df[cuisine_columns] = df['Cuisine'].str.split(', ', expand=True)

print(df.columns)
df.head()

Index(['Name', 'Address', 'Location', 'Price', 'Cuisine', 'Longitude',
       'Latitude', 'PhoneNumber', 'Url', 'WebsiteUrl', 'Award',
       'FacilitiesAndServices', 'Description', 'Locality', 'Country',
       'Cuisine 1', 'Cuisine 2'],
      dtype='object')

,Name,Address,Location,Price,Cuisine,Longitude,Latitude,PhoneNumber,Url,WebsiteUrl,Award,FacilitiesAndServices,Description,Locality,Country,Cuisine 1,Cuisine 2
0,L'OSIER,"7-5-5 Ginza, Chuo-ku, Tokyo, 104-0061, Japan","Tokyo, Japan",Muy costoso,"French, Contemporary",139.761203,35.669667,8.133572e+10,https://guide.michelin.com/en/tokyo-region/tok...,https://losier.shiseido.co.jp/,3 Stars,"Air conditioning,Car park,Interesting wine list",In 2023 L’OSIER celebrated the 50th anniversar...,Tokyo,Japan,French,Contemporary
1,Azabu Kadowaki,"2-7-2 Azabujuban, Minato-ku, Tokyo, 106-0045, ...","Tokyo, Japan",Muy costoso,Japanese,139.733551,35.655993,8.135772e+10,https://guide.michelin.com/en/tokyo-region/tok...,NaN,3 Stars,"Air conditioning,Counter dining",Toshiya Kadowaki’s aim is to serve up “unforge...,Tokyo,Japan,Japanese,None
2,Kohaku,"3-4 Kagurazaka, Shinjuku-ku, Tokyo, 162-0825, ...","Tokyo, Japan",Muy costoso,Japanese,139.741008,35.700701,8.150314e+11,https://guide.michelin.com/en/tokyo-region/tok...,http://kagurazaka-kohaku.jp/,3 Stars,"Air conditioning,Counter dining,Interesting wi...",Koji Koizumi creates a cuisine all his own as ...,Tokyo,Japan,Japanese,None
3,Harutaka,"6F, 8-3-1 Ginza, Chuo-ku, Tokyo, 104-0061, Japan","Tokyo, Japan",Muy costoso,Sushi,139.759203,35.669269,8.133573e+10,https://guide.michelin.com/en/tokyo-region/tok...,NaN,3 Stars,"Air conditioning,Counter dining",Sometimes our connections intervene to change ...,Tokyo,Japan,Sushi,None
4,Kanda,"1F, Toranomon Hills Residential Tower, 1-1-1 A...","Tokyo, Japan",Muy costoso,Japanese,139.748000,35.665800,8.136459e+10,https://guide.michelin.com/en/tokyo-region/tok...,http://www.nihonryori-kanda.com/,3 Stars,"Air conditioning,Counter dining,Interesting wi...",Hiroyuki Kanda understands the essence of Japa...,Tokyo,Japan,Japanese,None

In [14]:
# Filtrar por columnas 'Award'
df = df[df['Award'].isin(['1 Start', '2 Starts', '3 Starts'])]

In [17]:
# Establecer un máximo deseado de etiquetas
max_facilities_labels = 5

# Dividir 'FacilitiesAndServices' y expandir en columnas
split_columns = df['FacilitiesAndServices'].str.split(', ', n=max_facilities_labels - 1, expand=True)

# Concatenar las nuevas columnas al DataFrame original
df = pd.concat([df, split_columns], axis=1)

# Eliminar la columna original 'FacilitiesAndServices' si es necesario
df = df.drop('FacilitiesAndServices', axis=1)

# Renombrar las nuevas columnas
df.columns = df.columns[:len(df.columns)-max_facilities_labels].tolist() + [f'Facilities_{i}' for i in range(1, max_facilities_labels + 1)]

print(df.columns)

KeyError: 'FacilitiesAndServices'

In [18]:
# Imprimir el DataFrame resultante
print(df.head())

Empty DataFrame
Columns: [Name, Address, Location, Price, Cuisine, Longitude, Latitude, PhoneNumber, Url, WebsiteUrl, Award, Facilities_1, Facilities_2, Facilities_3, Facilities_4, Facilities_5]
Index: []

In [ ]:
try:
    connection = mysql.connector.connect(host='localhost',
                                       database='base_de_datos',
                                       user='usuario',
                                       password='contraseña')

    if connection.is_connected():
        cursor = connection.cursor()
        print("Conexión establecida")
except Error as e:
    print(f"Error: {e}")

In [ ]:
table_name = 'nombre_de_tu_tabla'
df.to_sql(name=table_name, con=connection, if_exists='replace', index=False)